//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1_7_1 {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new _1_7_1.SiteTemplate Master {
            get {
                return ((_1_7_1.SiteTemplate)(base.Master));
            }
        }
    }
}
